try {
} catch {
}

class Exception {
}

try {
} catch(Exception) {
}

try {
} catch(Exception e) {
}

try {
} catch(e) { // Nothing was thrown so we skip over 'e' without noticing that it's undefined.
}

// try {
// } catch(Exception) {
// } catch(Exception) {
// }

// try {
// } catch(Exception) {
// } catch {
// }

try {
} catch(Exception e) {
	print(e);
}

try {
} catch {
	print("Unreachable");
}
